import { useEffect, useState } from "react";
import { integrationService, type AdminIntegration, type ConfigureIntegrationRequest, type SetupField } from "@/services/integrationService";
import { useIntegrationStore } from "@/stores/integrationStore";
import { IntegrationStatusBadge, issueMessage, statusDescription } from "@/utils/integrationPresentation";

type FormValues = Record<string, string | boolean>;
const fieldKind = (field: SetupField): "text" | "secret" | "boolean" | "select" => {
  if (field.secret) return "secret";
  if (field.field_type === "boolean") return "boolean";
  if (field.field_type === "select") return "select";
  return "text";
};

export function SecretField({ field, value, onChange, configured }: { field: SetupField; value: string; onChange: (value: string) => void; configured: boolean }) {
  return <label className="block text-sm text-ac-ink" htmlFor={`setup-${field.key}`}>{field.label}<span className="ml-2 text-xs text-ac-muted">{configured ? "Configured" : "Not configured"}</span><input id={`setup-${field.key}`} type="password" autoComplete="new-password" value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded border border-ac-border bg-ac-surface px-3 py-2" aria-describedby={`setup-${field.key}-description`} /><span id={`setup-${field.key}-description`} className="text-xs text-ac-muted">Leave blank to keep the current value.</span></label>;
}

export function AdminIntegrationForm({ definitionId, fields, configuredFields = [], onSubmit }: { definitionId: string; fields: SetupField[]; configuredFields?: Array<{ key: string; configured: boolean; value: null }>; onSubmit: (request: ConfigureIntegrationRequest) => Promise<unknown> }) {
  const [values, setValues] = useState<FormValues>({}); const [submitting, setSubmitting] = useState(false);
  const setValue = (key: string, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }));
  return <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); setSubmitting(true); const entries: Array<[string, ConfigureIntegrationRequest["values"][string]]> = []; fields.forEach((field) => { const value = values[field.key]; if (field.secret && (!value || typeof value !== "string")) return; if (fieldKind(field) === "boolean") entries.push([field.key, { kind: "boolean", value: value === true }]); else entries.push([field.key, { kind: field.secret ? "secret" : "text", value: typeof value === "string" ? value : "" }]); }); const request: ConfigureIntegrationRequest = { definition_id: definitionId, enabled_capabilities: [], values: Object.fromEntries(entries) }; void onSubmit(request).finally(() => { setValues((current) => Object.fromEntries(Object.entries(current).map(([key, value]) => [key, fields.find((field) => field.key === key)?.secret ? "" : value]))); setSubmitting(false); }); }}>
    {fields.map((field) => { const value = values[field.key]; const configured = configuredFields.find((candidate) => candidate.key === field.key)?.configured ?? false; if (fieldKind(field) === "secret") return <SecretField key={field.key} field={field} value={typeof value === "string" ? value : ""} configured={configured} onChange={(next) => setValue(field.key, next)} />; if (fieldKind(field) === "boolean") return <label key={field.key} className="flex gap-2 text-sm text-ac-ink"><input type="checkbox" checked={value === true} onChange={(event) => setValue(field.key, event.target.checked)} />{field.label}</label>; return <label key={field.key} className="block text-sm text-ac-ink" htmlFor={`setup-${field.key}`}>{field.label}<input id={`setup-${field.key}`} value={typeof value === "string" ? value : ""} onChange={(event) => setValue(field.key, event.target.value)} required={field.required} className="mt-1 w-full rounded border border-ac-border bg-ac-surface px-3 py-2" /></label>; })}
    <button disabled={submitting} type="submit" className="ac-btn px-3 py-1.5 text-xs">{submitting ? "Saving…" : "Save setup"}</button>
  </form>;
}

export function AdminDiagnosticsPanel({ integration }: { integration: AdminIntegration }) { const [open, setOpen] = useState(false); const diagnostics = integration.diagnostics; return <section className="rounded border border-ac-border p-3"><button type="button" className="text-sm font-medium text-ac-ink" aria-expanded={open} onClick={() => setOpen(!open)}>Diagnostics</button>{open && <dl className="mt-3 text-sm text-ac-muted"><dt>Last health check</dt><dd>{diagnostics?.last_health_check ?? "Not available"}</dd><dt className="mt-2">Errors</dt><dd>{diagnostics?.error_count ?? 0}</dd><dt className="mt-2">Last issue</dt><dd>{diagnostics?.last_error ? "A connection issue was recorded." : "None"}</dd></dl>}</section>; }

export function AdminIntegrationDetail({ integration, onBack }: { integration: AdminIntegration; onBack: () => void }) { const configure = useIntegrationStore((s) => s.configure); const enable = useIntegrationStore((s) => s.enable); const disable = useIntegrationStore((s) => s.disable); const test = useIntegrationStore((s) => s.test); const remove = useIntegrationStore((s) => s.remove); const [result, setResult] = useState(""); return <section className="max-w-2xl space-y-4"><button className="text-sm text-ac-brand" onClick={onBack}>Back to integrations</button><h1 className="text-xl font-semibold text-ac-ink">{integration.display_name}</h1><p className="text-sm text-ac-muted">Management: {integration.management}</p><IntegrationStatusBadge status={integration.status} /><p className="text-sm text-ac-muted">{statusDescription(integration.status)}</p><AdminIntegrationForm definitionId={integration.definition_id} fields={integration.setup_schema} configuredFields={integration.configured_fields} onSubmit={configure} /><div className="flex gap-2"><button className="ac-btn px-3 py-1.5 text-xs" onClick={() => void enable(integration.id)}>Enable</button><button className="rounded border border-ac-border px-3 py-1.5 text-xs" onClick={() => void disable(integration.id)}>Disable</button><button className="rounded border border-ac-border px-3 py-1.5 text-xs" onClick={() => void test(integration.id).then((value) => setResult(`Connection check: ${value.status}`))}>Test</button><button className="rounded border border-ac-brand px-3 py-1.5 text-xs text-ac-brand" onClick={() => { if (confirm(`Remove ${integration.display_name}?`)) void remove(integration.id).then(onBack); }}>Remove</button></div><p aria-live="polite" className="text-sm text-ac-muted">{result}</p><AdminDiagnosticsPanel integration={integration} /></section>; }

export function AdminIntegrationOverview() { const instances = useIntegrationStore((s) => s.instances); const loadConfigured = useIntegrationStore((s) => s.loadConfigured); const handleEvent = useIntegrationStore((s) => s.handleEvent); const [selected, setSelected] = useState<AdminIntegration | null>(null); useEffect(() => { void loadConfigured(); let unlisten: (() => void) | undefined; void integrationService.subscribe(handleEvent).then((fn) => { unlisten = fn; }); return () => unlisten?.(); }, [handleEvent, loadConfigured]); if (selected) return <AdminIntegrationDetail integration={selected} onBack={() => setSelected(null)} />; const rows = Array.from(instances.values()).filter((view): view is { kind: "admin"; data: AdminIntegration } => view.kind === "admin").map((view) => view.data); return <section className="p-6"><h1 className="text-xl font-semibold text-ac-ink">Integration administration</h1><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-ac-muted"><tr><th>Definition</th><th>Instance</th><th>Management</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((integration) => <tr key={integration.id} className="border-t border-ac-border"><td>{integration.definition_id}</td><td>{integration.display_name}</td><td>{integration.management}</td><td><IntegrationStatusBadge status={integration.status} /></td><td><button className="text-ac-brand" onClick={() => setSelected(integration)}>Manage</button></td></tr>)}</tbody></table></div></section>; }

export { issueMessage };
